.editorconfig

This doesn't change what pylint enforces. It only changes what your code editor shows as the line limit.
This of course only works in code editors that use the `.editorconfig` file. Editors that do this natively are:
* PyCharm
* VisualStudio
There are also Plugins for the following editors:
* Atom
* VSCode
* eclipse
* emacs
* (many more)
source: https://editorconfig.org/#download

Add editorconfig with line length 100

---

ethicml/evaluators/evaluate_models.py
ethicml/evaluators/per_sensitive_attribute.py

This was causing a print every time `ethicml` was imported:
```
>>> import ethicml
Metric Not Applicable per sensitive attribute, apply to whole dataset instead
```
Apparently, you shouldn't put a print statement there. I followed this advice: https://www.programiz.com/python-programming/user-defined-exception to fix the problem.
Now it works nicely:
```
>>> import ethicml
>>> ethicml.evaluators.evaluate_models.per_sens_metrics_check([ethicml.metrics.CV()])
---------------------------------------------------------------------------
MetricNotApplicable                       Traceback (most recent call last)
<ipython-input-5-6062284beb0a> in <module>
1 import ethicml
----> 2 ethicml.evaluators.evaluate_models.per_sens_metrics_check([ethicml.metrics.CV()]) …
```

Remove print statement from exception definition

---

ethicml/algorithms/utils.py
ethicml/evaluators/evaluate_models.py
tests/metric_test.py

There is right now unfortunately a lot of code duplication between `evaluate_models()` and `evaluate_threaded_models()`. (Fortunately or unfortunately, pylint only cares about similarities between different files.) This duplication can hopefully be significantly reduced later. I didn't want to put too much work into de-duplication only for us to delete one of the two functions.

Add evaluation loop for threaded algorithms

---

setup.py

`distutils` is old and lacks some features. In particular, I found that `pip install -e .` was not working correctly with distutils. Using setuptools has solved that problem.

Use setuptools instead of distutils in setup.py

---

ethicml/algorithms/algorithm_base.py
ethicml/algorithms/inprocess/in_algorithm.py
ethicml/algorithms/inprocess/installed_model.py
ethicml/algorithms/inprocess/logistic_regression.py
ethicml/algorithms/inprocess/logistic_regression_cross_validated.py
ethicml/algorithms/inprocess/logistic_regression_probability.py
ethicml/algorithms/inprocess/svm.py
ethicml/implementations/common_in.py
ethicml/implementations/logistic_regression.py
ethicml/implementations/logistic_regression_cross_validated.py
ethicml/implementations/logistic_regression_probability.py
ethicml/implementations/svm.py

This PR adds a new submodule: `ethicml.implementations`. This submodule contains the actual implementations of the algorithms.
This separation has the following advantages:
* python packages that are used in the implementations can be loaded on demand
* files don't call themselves anymore
This will make it much easier to understand what is going on. No more `self.module` references that are hidden in some base classes.
* the classes `Algorithm` and `InAlgorithm` were able to get rid of a lot of code that is irrelevant to the algorithm objects. For example: previously each algorithm object previously stored the commandline arguments of the *current* program, even though these are completely irrelevant (only the commandline arguments of subprocesses are relevant)
* the code in …

Separate implementation of algorithms from class definition of the algorithms

---

ethicml/algorithms/inprocess/__init__.py
ethicml/algorithms/inprocess/agarwal_reductions.py
ethicml/algorithms/inprocess/in_algorithm.py
ethicml/algorithms/inprocess/installed_model.py
ethicml/algorithms/inprocess/kamiran.py
ethicml/algorithms/inprocess/logistic_regression.py
ethicml/algorithms/inprocess/logistic_regression_cross_validated.py
ethicml/algorithms/inprocess/logistic_regression_probability.py
ethicml/algorithms/inprocess/majority.py
ethicml/algorithms/inprocess/mlp.py
ethicml/algorithms/inprocess/svm.py
ethicml/algorithms/preprocess/__init__.py
ethicml/algorithms/preprocess/beutel.py
ethicml/algorithms/preprocess/pre_algorithm.py
ethicml/algorithms/preprocess/vfae.py
ethicml/algorithms/preprocess/zemel.py
ethicml/evaluators/evaluate_models.py
ethicml/evaluators/parallelism.py
tests/models_inprocessing_test.py
tests/models_preprocessing_test.py
tests/saving_data_test.py

`InAlgorithm` -> `InAlgorithmAsync`
`InAlgorithmSync` -> `InAlgorithm`
`PreAlgorithm` -> `PreAlgorithmAsync`
`PreAlgorithmSync` -> `PreAlgorithm`

Rename classes to make hierarchy more intuitive

---

ethicml/implementations/zemel.py

It turns out, Zemel is implementing his own manual matrix multiplication, so it doesn't even matter if np.matrix or np.ndarray is used...

Replace matrix object with np.ndarray

---

ethicml/algorithms/inprocess/logistic_regression.py
tests/models_inprocessing_test.py
tests/models_preprocessing_test.py

This is so that you can compare the results of cross validations.

Put the value of the C parameter in the name of LR

---

README.md
setup.py

Having a specific torch version in the requirements only causes problems it seems.
To make matters worse, it seems that on Windows, you can't install pytorch from pypi at all! You *always* have to install it via a download URL like this
```shell
pip install https://download.pytorch.org/whl/cpu/torch-1.0.1-cp36-cp36m-win_amd64.whl
```
I don't think we can cover all these special cases in our `setup.py`.

Make PyTorch a dev requirement only

---

ethicml/vision/data/celeba.py

What mypy really was complaining about there in celeba.py wasn't the fact that it wasn't strings, it was the fact that it wasn't a list. So the `map(str, ...)` wasn't actually needed.

Slight improvement that came to me in a dream

---

ethicml/data/adult.py
ethicml/data/load.py
run_mypy.py
run_mypy_tests.py
tests/loading_data_test.py

This was harder to do than I thought. The problem is that the list of
features has to match what is in the CSV file. But in our case, that is
explicitly not what we want to do.
A slightly confusing aspect of this solution now is that
`disc_feature_groups` and `discrete_features` are a bit out of sync.
`disdisc_feature_groups` has some features that are not listed in
`discrete_features`. I don't think it's too bad though because code that
makes use of `discrete_features` is very low level code anyway and the
programmer who writes it can be expected to know about this subtlety.

Ensure that all feature groups have at least two elements

---

ethicml/implementations/dro_modules/dro_loss.py

I think `.square()` was added in pytorch 1.5.

The .square() method is too new; fall back to .pow(2)

---

.github/workflows/continuous_integration.yml
check_all.py
ethicml/evaluators/cross_validator.py
ethicml/evaluators/evaluate_models.py
ethicml/utility/data_structures.py
ethicml/visualisation/plot.py
run_pydocstyle.py
tests/models_test/inprocess_test/cv_test.py
tests/models_test/inprocess_test/models_inprocessing_test.py
tests/run_algorithm_test.py
tests/visualisation_test.py

It was getting annoying to always do `results.data` to access the
underlying dataframe. Now that Results is just a NewType wrapper around
DataFrame, you don't have to do this anymore. The price we pay for this
is that all the class methods have to be turned into normal functions
which is a bit ugly, but the "enduser" will likely never deal with them.
(The only place in the code where this comes up is in evaluate_models).

Turn the Results class into a NewType(DataFrame)

---

.github/workflows/continuous_integration.yml
.pylintrc
ethicml/vision/data/dataset_wrappers.py
ethicml/visualisation/plot.py
setup.py

There is still plenty for pylint to complain about:
```
************* Module ethicml.metrics.cv
/Users/tk324/PycharmProjects/ethicml/ethicml/metrics/cv.py:   18, 8: Import outside toplevel (ethicml.evaluators.per_sensitive_attribute.metric_per_sensitive_attribute, ethicml.evaluators.per_sensitive_attribute.diff_per_sensitive_attribute) (import-outside-toplevel)
************* Module ethicml.metrics.dependence_measures
/Users/tk324/PycharmProjects/ethicml/ethicml/metrics/dependence_measures.py:   91,24: Variable name "l" doesn't conform to '(([a-z][a-z0-9_]{2,30})|(_[a-z0-9_]*))$' pattern (invalid-name)
************* Module ethicml.vision.data.transforms
/Users/tk324/PycharmProjects/ethicml/ethicml/vision/data/transforms.py:   12, 4: Method could be a function (no-self-use) …
```

Disable pylint errors already covered by mypy/pydocstyle

---

ethicml/__init__.py
ethicml/algorithms/preprocess/__init__.py
ethicml/algorithms/preprocess/beutel.py
ethicml/algorithms/preprocess/calders.py
ethicml/algorithms/preprocess/pre_algorithm.py
ethicml/algorithms/preprocess/upsampler.py
ethicml/algorithms/preprocess/vfae.py
ethicml/algorithms/preprocess/zemel.py
ethicml/utility/__init__.py
ethicml/utility/activation.py
ethicml/utility/heaviside.py

Is there a reason not to do this?
(`ethicml.implementations` and `ethicml.vision` are of course not automatically imported, because they require pytorch.)

Import everything in ethicml into one namespace

---

setup.py

The pillow dependency was only there because one version of pytorch had a problem with pillow 7.0. But this is not the case anymore, so we're not requiring any specific version of pillow.

Remove pillow version and fix version number on master

---

ethicml/common.py
ethicml/data/vision_data/celeba.py
tests/conftest.py
tests/loading_data_test.py

This turned out to be a bit tricky. It seems the best way to do this is to have a central point that checks if torch can be imported and which then sets a global variable. Then, in the tests we can manipulate that variable to make the code think that torch is not installed.

Write tests to simulate the case where no pytorch is available

---

ethicml/evaluators/evaluate_models.py

This would be useful when the sensitive attribute is very high-dimensional, because in that case there would be a very large number of diffs and ratios (they're computed pair-wise).

Add option to turn off diffs and ratios

---

.github/workflows/continuous_integration.yml
ethicml/algorithms/postprocess/hardt.py
ethicml/data/dataset.py
ethicml/implementations/pytorch_common.py
ethicml/implementations/zemel.py
ethicml/metrics/confusion_matrix.py
ethicml/metrics/dependence_measures.py
ethicml/metrics/hsic.py
ethicml/metrics/prob_outcome.py
ethicml/preprocessing/adjust_labels.py
ethicml/preprocessing/train_test_split.py
ethicml/vision/data/cmnist.py
ethicml/vision/data/image_dataset.py
mypy.ini
run_mypy_tests.py
setup.py
tests/run_algorithm_test.py
tests/saving_data_test.py

Instead we use the pandas type stubs from https://github.com/microsoft/python-type-stubs and the numpy type stubs that are now directly integrated in numpy.

Don't use type stubs from data-scienc-types anymore

---

.github/workflows/dependabot_auto.yml

I'm tempted to make the workflow dir trigger the dummy CI rather than the real one

add guard that ci workflow passes successfully

---

ethicml/algorithms/inprocess/svm.py
tests/models_test/inprocess_test/models_inprocessing_test.py
tests/models_test/preprocess_test/models_preprocessing_test.py

This technically breaks backwards compatibility with respect to the algorithm name (which is why I didn’t do it before), but I don’t really think it’s that bad.
This will not help with your configen problem though, Oliver. For that, we'd need to convert the Literal to an enum.

Turn SVM model class into a dataclass

---

ethicml/data/tabular_data/admissions.py
ethicml/data/tabular_data/adult.py
ethicml/data/tabular_data/compas.py
ethicml/data/tabular_data/credit.py
ethicml/data/tabular_data/crime.py
ethicml/data/tabular_data/german.py
ethicml/data/tabular_data/health.py
ethicml/data/tabular_data/law.py
ethicml/data/tabular_data/sqf.py
tests/data_omegaconf_test.py
tests/loading_data_test.py

They are not real type aliases though and can't be used for type annotations.
This is a backport of  #587.

Add aliases for dataset splits within the dataset classes

---

ethicml/implementations/agarwal.py
poetry.lock
pyproject.toml

Why, you ask? Mostly to reduce the number of dependencies.

Update fairlearn to 0.7.0

---

.github/workflows/continuous_integration.yml
poetry.lock
pyproject.toml

Having PyTorch in the dependencies only causes problems. You won't get the right version anyway with poetry and just the presence of PyTorch in the dependencies slows down `poetry update` enormously. It's just not worth it.

Update OmegaConf and remove PyTorch from dependencies

---

.github/workflows/continuous_integration.yml

Instead of caching the whole python venv, we'll only cache poetry's cache. The main advantage is that this won't be so quickly invalidated.

Use a new caching strategy for the CI

---

ethicml/models/algorithm_base.py
ethicml/models/inprocess/installed_model.py
ethicml/models/inprocess/kamishima.py
ethicml/models/inprocess/zafar.py
tests/models_test/inprocess_test/zafar_test.py

Depends on this branch: https://github.com/wearepal/fair-classification/tree/python3

Update Zafar to Python 3

---

ethicml/implementations/beutel.py

I guess when the code was written, torch.bool didn't exist.

Use bool mask
