azure-pipelines.yml, check_all.py, ethicml/algorithms/preprocess/beutel.py, mypy.ini, requirements.txt, run_mypy.py, run_pylint.py
* add mypy.ini
* add run_mypy.py
* add check_all.py
* run run_mypy.py on Azure
=> Use mypy to check the code

ethicml/algorithms/algorithm_base.py, ethicml/algorithms/dataloader_funcs.py, ethicml/algorithms/inprocess/__init__.py, ethicml/algorithms/inprocess/threaded/__init__.py, ethicml/algorithms/inprocess/threaded/logistic_regression.py, ethicml/algorithms/inprocess/threaded/threaded_in_algorithm.py, ethicml/algorithms/utils.py, ethicml/evaluators/evaluate_models.py, examples/logistic_regression.py, requirements.txt, tests/run_algorithm_test.py, tests/saving_data_test.py
=> Run algorithms in their own process

ethicml/algorithms/preprocess/threaded/__init__.py, ethicml/algorithms/preprocess/threaded/threaded_pre_algorithm.py
This is modeled very closely by the threaded in-algorithms.
=> Add threaded pre-algorihm base classes

ethicml/algorithms/utils.py, ethicml/evaluators/evaluate_models.py, ethicml/metrics/eq_opp_prob_pos.py, tests/run_algorithm_test.py
I should have removed it when I introduced `DataTuple`s.
=> Remove make_data_tuple()

ethicml/data/__init__.py, tests/loading_data_test.py, tests/metric_test.py, tests/run_algorithm_test.py
This is similar to #24 but with the datasets.
=> Make it easier to import the datasets

ethicml/algorithms/algorithm_base.py, ethicml/algorithms/inprocess/in_algorithm.py, ethicml/algorithms/inprocess/installed_model.py, ethicml/algorithms/inprocess/kamishima.py, ethicml/algorithms/preprocess/pre_algorithm.py, ethicml/algorithms/utils.py, ethicml/evaluators/evaluate_models.py, tests/saving_data_test.py
* Use Path objects instead of strings 
* Make `write_data()` a method of Algorithm
* Make `_load_output()` non-private
* Re-structure the Kamishima wrapper
* Pull `run_threaded` out of Pre-/In-Algorithm
=> Change the algorithm API such that it can better accomodate algorithms like Kamishima

ethicml/metrics/confusion_matrix.py
This is still missing tests. I'll add them after the deadline. It's not really important right now.
=> Make labels an array instead of a list

ethicml/algorithms/algorithm_base.py, ethicml/algorithms/inprocess/fair_gpyt.py, ethicml/algorithms/inprocess/in_algorithm.py, ethicml/algorithms/inprocess/kamishima.py, ethicml/algorithms/preprocess/pre_algorithm.py, ethicml/evaluators/__init__.py, ethicml/evaluators/evaluate_models.py, ethicml/evaluators/parallelism.py, tests/run_algorithm_test.py
You can try it out with
```python
lr_result, svm_result, maj_result = run_in_parallel([LR(), SVM(), Majority()], data)
```
=> Run algorithms embarrassingly parallel

ethicml/algorithms/preprocess/beutel.py, ethicml/algorithms/preprocess/interface.py, ethicml/implementations/beutel.py, ethicml/implementations/utils.py, ethicml/implementations/vfae_modules/vfae_network.py, ethicml/implementations/zemel.py
Dictionaries cannot be typed; so we're using a dataclass now.
=> Don't use a dict for the flags in Beutel

setup.py
and institute as the author over the individual
=> version number

ethicml/algorithms/__init__.py, ethicml/data/__init__.py, ethicml/evaluators/__init__.py, ethicml/metrics/__init__.py, ethicml/preprocessing/__init__.py, ethicml/utility/__init__.py, ethicml/visualisation/__init__.py, tests/conftest.py, tests/loading_data_test.py, tests/metric_test.py, tests/models_inprocessing_test.py, tests/models_preprocessing_test.py, tests/preprocessing_test.py, tests/run_algorithm_test.py, tests/saving_data_test.py, tests/visualisation_test.py
=> Limit the depth of the API

.pylintrc, ethicml/algorithms/inprocess/fair_gpyt.py, ethicml/algorithms/inprocess/in_algorithm.py, ethicml/algorithms/inprocess/installed_model.py, ethicml/algorithms/inprocess/kamishima.py, ethicml/algorithms/preprocess/__init__.py, tests/models_inprocessing_test.py
When certain arguments are passed to the constructor of the installed model, the model does not download the code and does not create a pipenv.
=> Add option to the Installed Model to not download

ethicml/utility/data_structures.py
I'm not sure if this is a good idea. I just realized that this is possible and wanted to try it out.
=> Move write_as_feather into DataTuple class

ethicml/algorithms/preprocess/pre_algorithm.py, ethicml/implementations/utils.py, tests/models_preprocessing_test.py
There were spurious files being created.
=> Fix a problem with dataset names

ethicml/visualisation/plot.py
=> Save plots as PDF

ethicml/evaluators/evaluate_models.py
The default order is much better.
=> Never sort columns in evaluate models

.pylintrc, ethicml/algorithms/inprocess/__init__.py, ethicml/algorithms/inprocess/agarwal_reductions.py, ethicml/algorithms/inprocess/fair_gpyt.py, ethicml/algorithms/preprocess/beutel.py, ethicml/implementations/agarwal.py, ethicml/implementations/beutel.py, ethicml/utility/__init__.py, ethicml/utility/data_structures.py, ethicml/visualisation/common.py, tests/local_installed_lr.py, tests/models_inprocessing_test.py, tests/models_preprocessing_test.py, type_defs/matplotlib/pyplot.pyi, type_defs/pandas/_core.pyi
With mypy's `Literal[]` we can achieve basically the same functionality that we had with Enum.
=> Use string literals instead of Enums for fairness type

.pylintrc, ethicml/algorithms/inprocess/fair_gpyt.py, ethicml/algorithms/postprocess/hardt.py, ethicml/implementations/pytorch_common.py, ethicml/implementations/zemel.py, ethicml/metrics/confusion_matrix.py, ethicml/metrics/hsic.py, ethicml/preprocessing/train_test_split.py, tests/models_postprocessing_test.py, tests/run_algorithm_test.py
The type stubs were changed here: https://github.com/predictive-analytics-lab/machine-learning-types/pull/12
=> Adapt to new numpy type stubs

ethicml/implementations/beutel.py, ethicml/implementations/upsampler.py, ethicml/implementations/utils.py, ethicml/implementations/vfae.py, ethicml/implementations/zemel.py, tests/models_inprocessing_test.py
Getting rid of 38 lines! While making the code more type safe!
=> Pass args object directly to load_data_from_flags()

.github/workflows/continuous_integration.yml, check_all.py, ethicml/evaluators/__init__.py, ethicml/evaluators/cross_validator.py, ethicml/evaluators/evaluate_models.py, ethicml/evaluators/parallelism.py, run_pydocstyle.py, setup.py, tests/models_inprocessing_test.py, tests/run_algorithm_test.py, tests/test_helpers.py
And also support pre-processing algorithms in `evaluate_models_parallel()`.
=> Make evaluate_models_parallel() an async function

ethicml/algorithms/inprocess/in_algorithm.py, ethicml/algorithms/inprocess/logistic_regression.py, ethicml/algorithms/inprocess/majority.py, ethicml/algorithms/inprocess/mlp.py, ethicml/algorithms/inprocess/svm.py, ethicml/evaluators/evaluate_models.py
I have some algorithms that take a long time to run and I don't want to run them on all the preprocessing methods.
=> Allow opting out of running a fair pipeline

ethicml/evaluators/evaluate_models.py, ethicml/visualisation/plot.py, tests/run_algorithm_test.py
And add the option to the async evaluate_models as well.
=> Add test for the fair pipeline option

ethicml/evaluators/evaluate_models.py, ethicml/evaluators/parallelism.py
The smoothing is a moving average which we don't want in our case.
=> Turn off smoothing for the long-running tqdm progress bars

ethicml/algorithms/algorithm_base.py, ethicml/algorithms/inprocess/agarwal_reductions.py, ethicml/algorithms/inprocess/in_algorithm.py, ethicml/algorithms/inprocess/installed_model.py, ethicml/algorithms/inprocess/kamiran.py, ethicml/algorithms/inprocess/kamishima.py, ethicml/algorithms/inprocess/logistic_regression.py, ethicml/algorithms/inprocess/majority.py, ethicml/algorithms/inprocess/manual.py, ethicml/algorithms/inprocess/mlp.py, ethicml/algorithms/inprocess/svm.py, ethicml/algorithms/inprocess/zafar.py, ethicml/algorithms/postprocess/hardt.py, ethicml/algorithms/preprocess/beutel.py, ethicml/algorithms/preprocess/calders.py, ethicml/algorithms/preprocess/upsampler.py, ethicml/algorithms/preprocess/vfae.py, ethicml/algorithms/preprocess/zemel.py, tests/models_inprocessing_test.py, tests/models_preprocessing_test.py, tests/saving_data_test.py
=> Let Algorithm base class handle the name property

ethicml/algorithms/inprocess/__init__.py, ethicml/algorithms/inprocess/agarwal_reductions.py, ethicml/algorithms/inprocess/in_algorithm.py, ethicml/algorithms/inprocess/installed_model.py, ethicml/algorithms/inprocess/kamiran.py, ethicml/algorithms/inprocess/kamishima.py, ethicml/algorithms/inprocess/logistic_regression.py, ethicml/algorithms/inprocess/majority.py, ethicml/algorithms/inprocess/manual.py, ethicml/algorithms/inprocess/mlp.py, ethicml/algorithms/inprocess/shared.py, ethicml/algorithms/inprocess/svm.py, ethicml/algorithms/inprocess/zafar.py
Export compute weights from kamiran.py.
=> Update inprocess/__init__.py to use __all__ with wild imports.

.github/workflows/continuous_integration.yml
E.g., documentation or .gitignore
=> Don't run CI on PRs that don't change any python files

ethicml/algorithms/inprocess/agarwal_reductions.py, ethicml/algorithms/inprocess/in_algorithm.py, ethicml/algorithms/inprocess/installed_model.py, ethicml/algorithms/inprocess/shared.py, ethicml/implementations/agarwal.py, ethicml/implementations/utils.py, ethicml/utility/data_structures.py, run_mypy.py, run_mypy_tests.py, tests/local_installed_lr.py, tests/models_inprocessing_test.py, tests/saving_data_test.py
This only affects inprocess algorithms right now.
=> Use numpy files instead of feather files, second attempt

ethicml/algorithms/inprocess/__init__.py, ethicml/algorithms/inprocess/svm_async.py, ethicml/implementations/svm.py, tests/models_inprocessing_test.py
SVM is just so slow that I really miss the asyncronous one.
=> Re-add async SVM

ethicml/algorithms/inprocess/logistic_regression.py, ethicml/algorithms/inprocess/svm.py, tests/models_test/inprocess_test/models_inprocessing_test.py, tests/models_test/postprocess_test/models_postprocessing_test.py, tests/models_test/preprocess_test/models_preprocessing_test.py
=> Fix naming of SVM object

ethicml/algorithms/inprocess/logistic_regression.py
Use a random state to make this reproducible.
=> Shuffle the data before folding in LRCV

.pre-commit-config.yaml, ethicml/data/tabular_data/credit.py, ethicml/data/tabular_data/sqf.py, ethicml/utility/__init__.py, ethicml/utility/scaling.py, tests/dataset_modification_test.py, tests/loading_data_test.py, tests/utility_test.py
I wanted to add a function to do the scaling of continuous features. 
This led to deciding that the tests of the dataset loading could be parametrized (and I found a bug!). 
Somewhere along the way I decided to make a more stringent pre-commit
=> add scaling as a dataset modification.

ethicml/data/vision_data/genfaces.py
Still problems with this dataset...
=> Fix paths in genfaces

ethicml/__init__.py, tests/conftest.py, tests/loading_data_test.py, tests/metrics/metric_test.py, tests/metrics/nonparamaterized_metric_test.py, tests/metrics/per_sens_test.py, tests/models_test/inprocess_test/models_inprocessing_test.py, tests/preprocessing_test.py, tests/saving_data_test.py, tests/visualisation_test.py, tests/zafar_test.py
It's important to write the tests this way so that we don't forget to import functions into the top level of EthicML.
=> Only import from the top level module "ethicml" in the tests

ethicml/data/dataset.py, ethicml/data/util.py, ethicml/data/vision_data/celeba.py, tests/loading_data_test.py
The old name was very nondescriptive.
=> Rename PartialLabelSpec to LabelGroup

.github/workflows/continuous_integration.yml, ethicml/data/dataset.py, tests/loading_data_test.py
=> Make .cont_features private in the Dataset class

ethicml/data/dataset.py
`filename_or_path` also shouldn't be used by outside functions.
=> Rename more attributes of Dataset

ethicml/data/dataset.py, ethicml/evaluators/evaluate_models.py, ethicml/utility/data_structures.py, ethicml/vision/data/cmnist.py, tests/dataset_modification_test.py, tests/run_algorithm_test.py
Add a scaler option to evaluation. It's reasonabl ethat you would want to preprocess your data as part of an evaluation pipeline.
=> evaluation should use a scaler

make_release.sh, pyproject.toml
I also improved the release script a bit.
closes #435
=> Exclude raw CSVs files from the built Python wheel

.github/workflows/continuous_integration.yml
not entirely sure I've done this right tbh
=> try to emulate the poetry setup from conduit

ethicml/data/dataset.py, ethicml/data/tabular_data/acs_income.py, ethicml/data/tabular_data/adult.py, ethicml/data/tabular_data/compas.py, ethicml/implementations/vfae.py, ethicml/utility/data_structures.py, ethicml/vision/data/utils.py, pyproject.toml, tests/loading_data_test.py
This would obviate the need for (neo)configen when using EthicML with hydra.
I'm not sure whether this is a good idea. I only did it for Adult and COMPAS and I'm sure lots of tests will fail.
=> Try to turn datasets into dataclasses

ethicml/data/dataset.py, poetry.lock, pyproject.toml, tests/dataset_modification_test.py, tests/loading_data_test.py
- add method to load data in the AIF360 format
- mypy
This adds a small function that loads data in the AIF360 format so that you can use with their algorithms
=> aif converter

ethicml/data/dataset.py, ethicml/data/load.py, ethicml/data/tabular_data/acs.py, ethicml/data/tabular_data/admissions.py, ethicml/data/tabular_data/adult.py, ethicml/data/tabular_data/compas.py, ethicml/data/tabular_data/credit.py, ethicml/data/tabular_data/crime.py, ethicml/data/tabular_data/german.py, ethicml/data/tabular_data/health.py, ethicml/data/tabular_data/law.py, ethicml/data/tabular_data/lipton.py, ethicml/data/tabular_data/non_binary_toy.py, ethicml/data/tabular_data/sqf.py, ethicml/data/tabular_data/synthetic.py, ethicml/data/tabular_data/toy.py, ethicml/data/vision_data/celeba.py, ethicml/data/vision_data/genfaces.py, tests/hydra_compatibility_test.py
Well, except for ACS Income, because that one seems complicated.
=> Turn all datasets into dataclasses

.github/workflows/continuous_integration.yml, ethicml/algorithms/algorithm_base.py, ethicml/algorithms/inprocess/in_algorithm.py, ethicml/algorithms/inprocess/installed_model.py, ethicml/algorithms/inprocess/kamishima.py, ethicml/algorithms/inprocess/zafar.py, ethicml/algorithms/preprocess/pre_algorithm.py, ethicml/implementations/agarwal.py, pyproject.toml, tests/loading_data_test.py, tests/models_test/inprocess_test/models_inprocessing_test.py, tests/models_test/inprocess_test/zafar_test.py, tests/visualisation_test.py
Also, a lot of other things that caught my eye. For example the class hierarchy of InstalledModel was not correct, I think.
I re-activated the Kamishima unittest to actually test my changes, but we can deactivate it afterwards again.
=> Disentangle Kamishima into fit()/predict()

tests/models_test/inprocess_test/models_inprocessing_test.py, tests/run_algorithm_test.py, tests/visualisation_test.py
- Mark more tests as slow
- More tests marked as slow
=> Mark more tests as slow

ethicml/algorithms/inprocess/installed_model.py, ethicml/algorithms/inprocess/zafar.py, tests/models_test/inprocess_test/zafar_test.py
The CI doesn't run the Zafar tests, so you'll just have to believe me that it works.
=> Use fit()/predict() split for Zafar

tests/models_test/inprocess_test/models_inprocessing_test.py, tests/models_test/inprocess_test/zafar_test.py, tests/models_test/postprocess_test/models_postprocessing_test.py, tests/preprocessing_test.py, tests/run_algorithm_test.py
=> Replace count_true with np.count_nonzero

.github/workflows/continuous_integration.yml, poetry.lock, pyproject.toml
- Update black to the first non-beta version
- Limit the version of black in the CI
=> Update black to non-beta version

ethicml/__init__.py, ethicml/metrics/accuracy.py, ethicml/metrics/anti_spur.py, ethicml/metrics/average_odds.py, ethicml/metrics/balanced_accuracy.py, ethicml/metrics/bcr.py, ethicml/metrics/cv.py, ethicml/metrics/dependence_measures.py, ethicml/metrics/fnr.py, ethicml/metrics/fpr.py, ethicml/metrics/hsic.py, ethicml/metrics/metric.py, ethicml/metrics/npv.py, ethicml/metrics/ppv.py, ethicml/metrics/prob_neg.py, ethicml/metrics/prob_outcome.py, ethicml/metrics/prob_pos.py, ethicml/metrics/theil.py, ethicml/metrics/tnr.py, ethicml/metrics/tpr.py, ethicml/visualisation/plot.py, tests/metrics/metric_test.py, tests/metrics/omegaconf_test.py, tests/models_test/inprocess_test/models_inprocessing_test.py
Same as before with the datasets and algorithms.
=> Turn metrics into dataclasses

.github/workflows/docs.yml, docsource/source/conf.py, docsource/source/ethicml.algorithms.rst, docsource/source/ethicml.data.rst, docsource/source/ethicml.evaluators.rst, docsource/source/ethicml.metrics.rst
Some screenshots:
**current look**
**new look (light theme)**
**with table of contents at the side**
**dark mode**
=> Use new docs theme which supports dark mode

.github/workflows/dependabot_auto.yml
TBH, I have no idea if this will work. I just copied and merged the auto-approve and auto-merge yaml files [from here](https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/automating-dependabot-with-github-actions#approve-a-pull-request)
=> Enable Auto-merge of dependabot prs

ethicml/algorithms/inprocess/agarwal_reductions.py, ethicml/algorithms/inprocess/fairness_wo_demographics.py, ethicml/algorithms/inprocess/in_algorithm.py, ethicml/algorithms/inprocess/installed_model.py, ethicml/algorithms/inprocess/kamiran.py, ethicml/algorithms/inprocess/kamishima.py, ethicml/algorithms/inprocess/logistic_regression.py, ethicml/algorithms/inprocess/mlp.py, ethicml/algorithms/inprocess/svm.py, ethicml/algorithms/inprocess/zafar.py, ethicml/algorithms/postprocess/hardt.py, ethicml/algorithms/postprocess/post_algorithm.py, ethicml/algorithms/preprocess/pre_algorithm.py, ethicml/algorithms/preprocess/upsampler.py, tests/models_test/inprocess_test/models_inprocessing_test.py, tests/run_algorithm_test.py, tests/saving_data_test.py
To be honest, I don't know why I didn't do that in the first place.
=> Make `is_fairness_algo` a `ClassVar`

ethicml/algorithms/inprocess/kamiran.py, ethicml/algorithms/postprocess/hardt.py, ethicml/algorithms/preprocess/upsampler.py, ethicml/data/csvs/make_admissions_from_raw.py, ethicml/data/csvs/make_adult_from_raw.py, ethicml/data/csvs/make_health_from_raw.py, ethicml/data/dataset.py, ethicml/implementations/beutel.py, ethicml/implementations/dro_tabular.py, ethicml/implementations/pytorch_common.py, ethicml/implementations/vfae.py, ethicml/implementations/zemel.py, ethicml/metrics/confusion_matrix.py, ethicml/preprocessing/domain_adaptation.py, ethicml/utility/data_helpers.py, ethicml/vision/data/utils.py, ethicml/visualisation/plot.py, poetry.lock, pyproject.toml, tests/loading_data_test.py, tests/saving_data_test.py
This allowed me to remove a lot of type-ignore comments but I also had
to add some.
=> Update type stubs

ethicml/algorithms/inprocess/in_algorithm.py, ethicml/algorithms/preprocess/pre_algorithm.py, ethicml/evaluators/evaluate_models.py, ethicml/metrics/accuracy.py, ethicml/utility/data_structures.py, tests/metrics/metric_test.py
I'm under no impression that this is good. Indexing by S in EM should be so much more elegant
=> Add RobustAccuracy Metric

ethicml/algorithms/algorithm_base.py, ethicml/algorithms/inprocess/agarwal_reductions.py, ethicml/algorithms/inprocess/fairness_wo_demographics.py, ethicml/algorithms/inprocess/in_algorithm.py, ethicml/algorithms/inprocess/shared.py, ethicml/algorithms/preprocess/beutel.py, ethicml/algorithms/preprocess/interface.py, ethicml/algorithms/preprocess/pre_algorithm.py, ethicml/algorithms/preprocess/vfae.py, ethicml/algorithms/preprocess/zemel.py, ethicml/implementations/agarwal.py, ethicml/implementations/beutel.py, ethicml/implementations/dro_tabular.py, ethicml/implementations/utils.py, ethicml/implementations/vfae.py, ethicml/implementations/zemel.py, tests/models_test/inprocess_test/models_inprocessing_test.py, tests/saving_data_test.py, tests/visualisation_test.py
This allows us to remove lots of asserts.
=> Use a tagged union of TypedDict for the flags

ethicml/data/tabular_data/admissions.py, ethicml/data/tabular_data/adult.py, ethicml/data/tabular_data/compas.py, ethicml/data/tabular_data/credit.py, ethicml/data/tabular_data/crime.py, ethicml/data/tabular_data/german.py, ethicml/data/tabular_data/health.py, ethicml/data/tabular_data/law.py, ethicml/data/tabular_data/sqf.py, tests/hydra_compatibility_test.py, tests/loading_data_test.py
See here what it looks like:
https://github.com/predictive-analytics-lab/EthicML/blob/enum-aliases/tests/hydra_compatibility_test.py#L13
=> Add aliases for dataset splits within the dataset classes

ethicml/algorithms/inprocess/agarwal_reductions.py
I did this for testing, but we might as well keep it.
=> Turn Agarwal into a dataclass

ethicml/algorithms/preprocess/pre_subprocess.py, ethicml/implementations/beutel.py
I realized that you can call classmethods also on instances!
=> Fix a long-standing type error

ethicml/algorithms/inprocess/agarwal_reductions.py, ethicml/algorithms/preprocess/upsampler.py, ethicml/implementations/agarwal.py, ethicml/preprocessing/splits.py, ethicml/utility/data_structures.py
- Various improvements
- Export LabelTuple from data_structures
=> Various improvements

ethicml/implementations/adv_debiasing_method.py, ethicml/implementations/agarwal.py, ethicml/implementations/beutel.py, ethicml/implementations/dro_tabular.py, ethicml/implementations/fair_dummies_romano.py, ethicml/implementations/hgr_method.py, ethicml/implementations/utils.py, ethicml/implementations/vfae.py, ethicml/implementations/zemel.py, ethicml/models/inprocess/in_subprocess.py, ethicml/models/preprocess/pre_subprocess.py, ethicml/utility/data_structures.py, tests/saving_data_test.py
The idea is to make it future-compatible.
=> Rename to_npz and from_npz to not mention npz anymore

ethicml/data/dataset.py, make_release.sh, poetry.lock, pyproject.toml, tests/loading_data_test.py
This is a change to the 0.x branch. The problem does not exist on the 1.0 branch.
=> [0.x] Avoid infinite recursion on discrete_only

ethicml/data/csvs/make_nursery.py, ethicml/models/preprocess/calders.py, ethicml/models/preprocess/upsampler.py, ethicml/preprocessing/feature_binning.py, ethicml/preprocessing/splits.py, ethicml/utility/data_helpers.py, ethicml/utility/data_structures.py, poetry.lock, tests/data/dataset_modification_test.py
- Update pandas stubs
- Remove some type-ignore comments
=> update pandas stubs

pyproject.toml
- Bump version
- Bump version to prerelease
=> release 0.7.3

docs/conf.py, docs/ethicml/utility.rst, ethicml/evaluators/evaluate.py, ethicml/metrics/per_sensitive_attribute.py, ethicml/utility/data_structures.py, tests/metrics/nonparamaterized_metric_test.py, tests/metrics/per_sens_test.py
Also, try to improve docs a bit.
=> Use sets of enums instead of flags for metrics aggregation

ethicml/metrics/__init__.py, ethicml/metrics/eval.py, ethicml/run/evaluate.py, poetry.lock, tests/metrics/nonparamaterized_metric_test.py
I solemnly swear that this will be the last breaking change.
=> Move run_metrics

.github/workflows/continuous_integration.yml, .github/workflows/dummy_ci.yml, ethicml/utility/data_structures.py, pyproject.toml, tests/data/__init__.py, tests/data/data_omegaconf_test.py, tests/data/dataset_modification_test.py, tests/metrics/__init__.py, tests/metrics/metric_test.py, tests/metrics/nonparamaterized_metric_test.py, tests/metrics/omegaconf_test.py, tests/metrics/per_sens_test.py, tests/models_test/__init__.py, tests/models_test/inprocess_test/__init__.py, tests/models_test/inprocess_test/cv_test.py, tests/models_test/inprocess_test/models_inprocessing_test.py, tests/models_test/inprocess_test/omegaconf_test.py, tests/models_test/inprocess_test/zafar_test.py, tests/models_test/postprocess_test/__init__.py, tests/models_test/postprocess_test/models_postprocessing_test.py, tests/models_test/preprocess_test/__init__.py, tests/models_test/preprocess_test/models_preprocessing_test.py, tests/models_test/preprocess_test/omegaconf_test.py, tests/visualisation_test.py
- First steps of replacing isort with ruff
- Placate ruff
=> Use ruff instead of isort

ethicml/models/inprocess/svm.py
It's the same anyway, but maybe mypy will one day understand it this
way.
=> Use kernel.value instead of kernel.name

poetry.lock, pyproject.toml
=> Update to black 2023

.github/workflows/dependabot_auto.yml
It doesn't work with the merge queue.
=> Disable dependabot auto-merge

ethicml/plot/plotting.py
=> Fix multigrid plotting

.github/workflows/continuous_integration.yml, .github/workflows/dummy_ci.yml, docs/requirements.txt, poetry.lock
=> Clean up the CI

.github/workflows/continuous_integration.yml, ethicml/implementations/zemel.py, ethicml/metrics/accuracy.py, ethicml/metrics/dependence_measures.py, ethicml/models/inprocess/logistic_regression.py, ethicml/models/inprocess/mlp.py, ethicml/models/inprocess/shared.py, ethicml/models/inprocess/svm.py, ethicml/models/postprocess/hardt.py, poetry.lock, pyproject.toml
They do still provide some value.
=> Restore the use of python-type-stubs

.github/workflows/continuous_integration.yml, ethicml/data/csvs/make_admissions_from_raw.py, ethicml/data/csvs/make_law.py, ethicml/data/csvs/make_lipton.py, ethicml/data/csvs/make_non_binary_toy.py, ethicml/data/csvs/make_nursery.py, ethicml/data/csvs/make_toy_dataset.py, ethicml/data/tabular_data/acs.py, ethicml/implementations/adv_debiasing_modules/model.py, ethicml/implementations/fair_dummies_modules/utility_functions.py, ethicml/implementations/pytorch_common.py, ethicml/models/inprocess/in_subprocess.py, ethicml/models/inprocess/kamiran.py, ethicml/models/inprocess/mlp.py, ethicml/models/inprocess/zafar.py, ethicml/models/preprocess/pre_subprocess.py, ethicml/plot/plotting.py, ethicml/preprocessing/scaling.py, pyproject.toml, tests/models_test/inprocess_test/models_inprocessing_test.py
This is in preparation for switching to the ruff formatter.
=> Normalize strings with black

ethicml/implementations/dro_modules/dro_loss.py, ethicml/implementations/hgr_modules/facl/facl_hgr.py, ethicml/implementations/hgr_modules/facl_hgr.py, ethicml/run/cross_validator.py, ethicml/run/parallelism.py, ethicml/utility/data_helpers.py, poetry.lock, tests/conftest.py, tests/data/data_omegaconf_test.py, tests/data/dataset_modification_test.py, tests/data/loading_data_test.py, tests/local_installed_lr.py, tests/metrics/metric_test.py, tests/metrics/omegaconf_test.py, tests/metrics/per_sens_test.py, tests/models_test/inprocess_test/cv_test.py, tests/models_test/inprocess_test/models_inprocessing_test.py, tests/models_test/inprocess_test/omegaconf_test.py, tests/models_test/inprocess_test/zafar_test.py, tests/models_test/postprocess_test/models_postprocessing_test.py, tests/models_test/preprocess_test/models_preprocessing_test.py, tests/models_test/preprocess_test/omegaconf_test.py, tests/preprocessing_test.py, tests/run_algorithm_test.py, tests/saving_data_test.py, tests/utility_test.py, tests/visualisation_test.py
=> Don't use `type[T]`; use `Callable[..., T]`
